class LdifParser
  class EntryMaker
    def self.call: (String str) -> Hash[Symbol, Array[String]]
    def self.call_minimized: (String str) -> Hash[Symbol, (String | Array[String])]

    def initialize: (String str) -> void
    def make: -> Hash[Symbol, Array[String]]
    def make_minimized: -> Hash[Symbol, String | Array[String]]
    def lines_decoded_to_h: -> Hash[Symbol, Array[String]]
    def lines_decoded: -> Array[Array[String]]
    def line_decoder: (String line) -> Array[String]
    def lines: -> Array[String]
  end
end
